# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vulcan < Formula
  desc "Scanfold tool to create projects based on templates."
  homepage "https://github.com/caioeverest/vulcan"
  version "0.0.1"
  license "GPL-3.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/caioeverest/vulcan/releases/download/0.0.1/vulcan_0.0.1-macOS-x86_64.tar.gz"
    sha256 "a12967a76174dfc485e5c3d10e33a92923fe05715d91ef65f5f8f8ab50be2f56"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/caioeverest/vulcan/releases/download/0.0.1/vulcan_0.0.1-macOS-arm64.tar.gz"
    sha256 "10fd0a539955590411d0baf3ff52b6a3d06b48862e0cbe563be5827a2ea2ec6b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/caioeverest/vulcan/releases/download/0.0.1/vulcan_0.0.1-Linux-x86_64.tar.gz"
    sha256 "32a915988fadc0840a2fd2ade74f0910e2c907162e49d7639bb19e417b9e0978"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/caioeverest/vulcan/releases/download/0.0.1/vulcan_0.0.1-Linux-arm64.tar.gz"
    sha256 "16f801327756b2c5170b634c2c27395ff01541263f486891fb6e7b1f3ef241db"
  end

  depends_on "go"

  def install
    bin.install "vulcan"
  end

  test do
    system "#{bin}/vulcan -v"
  end
end
