# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vulcan < Formula
  desc "Scanfold tool to create projects based on templates."
  homepage "https://github.com/caioeverest/vulcan"
  version "0.0.1"
  license "GPL-3.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/caioeverest/vulcan/releases/download/0.0.1/vulcan_0.0.1-macOS-x86_64.tar.gz"
    sha256 "c85a187e5f71b5d8185c43187d3223b511dbc6740f81ab0988c019fb894550c1"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/caioeverest/vulcan/releases/download/0.0.1/vulcan_0.0.1-macOS-arm64.tar.gz"
    sha256 "b66d7846a8b9faa63d3f816893cb1f3b5880ef8b0ae0b4d0c339fbb695f88a56"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/caioeverest/vulcan/releases/download/0.0.1/vulcan_0.0.1-Linux-x86_64.tar.gz"
    sha256 "30cfe8ef012f8da4e1da5c9863068a152b260315a2e050230bd687b3437b0998"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/caioeverest/vulcan/releases/download/0.0.1/vulcan_0.0.1-Linux-arm64.tar.gz"
    sha256 "ced0f774ccf39b44426b0b10baa6cb2361190c7e14472b55b42de6bbf025f810"
  end

  depends_on "go"

  def install
    bin.install "vulcan"
  end

  test do
    system "#{bin}/vulcan -v"
  end
end
